// Catálogo de Productos - Frutería Mis Dos Angelitos (Oxkutzcab, Yucatán)
// Precios de menudeo: $5.00 - $50.00 MXN (por kg o pieza)
// Precios de mayoreo por huacal / caja (18-25kg): Máximo $500.00 MXN

const PRODUCTS = [
  // --- FRUTAS ---
  {
    id: 'naranja-dulce',
    name: 'Naranja Dulce de Oxkutzcab',
    category: 'frutas',
    isSeason: false,
    isPopular: true,
    origin: 'Oxkutzcab, Yucatán',
    icon: '🍊',
    retailPrice: 12.00,
    retailUnit: 'kg',
    wholesalePrice: 220.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Jugosa, dulce y recién cosechada de las huertas de Oxkutzcab. Excelente para jugos frescos.'
  },
  {
    id: 'limon-persa',
    name: 'Limón Persa',
    category: 'frutas',
    isSeason: false,
    isPopular: true,
    origin: 'Dzan / Oxkutzcab',
    icon: '🍋',
    retailPrice: 15.00,
    retailUnit: 'kg',
    wholesalePrice: 250.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Limón sin semilla, lleno de jugo y acidez perfecta para la cocina y limonadas.'
  },
  {
    id: 'mandarina',
    name: 'Mandarina Yucateca',
    category: 'frutas',
    isSeason: true,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🍊',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 280.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Fresco aroma cítrico y fácil de pelar. Selección especial de temporada.'
  },
  {
    id: 'mango-ataulfo',
    name: 'Mango Ataulfo',
    category: 'frutas',
    isSeason: true,
    isPopular: true,
    origin: 'Oxkutzcab / Akil',
    icon: '🥭',
    retailPrice: 35.00,
    retailUnit: 'kg',
    wholesalePrice: 450.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Carne cremosa, dulce y sin fibra. Calidad exportación directa del sur de Yucatán.'
  },
  {
    id: 'papaya-maradol',
    name: 'Papaya Maradol',
    category: 'frutas',
    isSeason: false,
    isPopular: true,
    origin: 'Maní / Oxkutzcab',
    icon: '🪺',
    retailPrice: 22.00,
    retailUnit: 'kg',
    wholesalePrice: 380.00,
    wholesaleUnit: 'Huacal (22 kg)',
    description: 'Rojas, dulces y en su punto ideal de maduración para consumo diario.'
  },
  {
    id: 'pitahaya',
    name: 'Pitahaya (Fruta del Dragón)',
    category: 'frutas',
    isSeason: true,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🌺',
    retailPrice: 45.00,
    retailUnit: 'kg',
    wholesalePrice: 490.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Exótica pitahaya yucateca de pulpa roja intensamente dulce y refrescante.'
  },
  {
    id: 'mamey',
    name: 'Mamey Yucateco',
    category: 'frutas',
    isSeason: true,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🥑',
    retailPrice: 40.00,
    retailUnit: 'pz',
    wholesalePrice: 480.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Textura cremosa y sabor único. Ideal para licuados y postres tradicionales.'
  },
  {
    id: 'sandia',
    name: 'Sandía Roja',
    category: 'frutas',
    isSeason: false,
    isPopular: false,
    origin: 'Región Sur',
    icon: '🍉',
    retailPrice: 10.00,
    retailUnit: 'kg',
    wholesalePrice: 220.00,
    wholesaleUnit: 'Caja Grande (25 kg)',
    description: 'Muy jugosa y refrescante. Perfecta para días calurosos.'
  },
  {
    id: 'melon',
    name: 'Melón Cantaloupe',
    category: 'frutas',
    isSeason: false,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🍈',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 300.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Dulce aroma y color anaranjado intenso.'
  },
  {
    id: 'pina',
    name: 'Piña Miel',
    category: 'frutas',
    isSeason: false,
    isPopular: true,
    origin: 'Región Sur',
    icon: '🍍',
    retailPrice: 25.00,
    retailUnit: 'pz',
    wholesalePrice: 350.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Piña miel extra dulce, perfecta para consumo fresco y jugos.'
  },
  {
    id: 'platano',
    name: 'Plátano Roatán',
    category: 'frutas',
    isSeason: false,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🍌',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 260.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Plátanos frescos seleccionados para óptima maduración.'
  },
  {
    id: 'guanabana',
    name: 'Guanábana Fresca',
    category: 'frutas',
    isSeason: true,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🍈',
    retailPrice: 40.00,
    retailUnit: 'kg',
    wholesalePrice: 480.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Pulpa suave y aromática ideal para aguas frescas y champolas.'
  },
  {
    id: 'ciruela',
    name: 'Ciruela Yucateca',
    category: 'frutas',
    isSeason: true,
    isPopular: true,
    origin: 'Dzan / Oxkutzcab',
    icon: '🔴',
    retailPrice: 30.00,
    retailUnit: 'kg',
    wholesalePrice: 360.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Fruta de temporada muy apreciada en la región, dulce y ácida.'
  },
  {
    id: 'zapote',
    name: 'Zapote Negro',
    category: 'frutas',
    isSeason: true,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🤎',
    retailPrice: 35.00,
    retailUnit: 'kg',
    wholesalePrice: 420.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Sabor dulce tipo chocolate, ideal para preparar dulces tradicionales.'
  },
  {
    id: 'tamarindo',
    name: 'Tamarindo Natural',
    category: 'frutas',
    isSeason: false,
    isPopular: false,
    origin: 'Akil',
    icon: '🟤',
    retailPrice: 35.00,
    retailUnit: 'kg',
    wholesalePrice: 400.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Vaina de tamarindo natural para refrescos y salsas.'
  },
  {
    id: 'coco',
    name: 'Coco con Agua',
    category: 'frutas',
    isSeason: false,
    isPopular: false,
    origin: 'Costa / Sur',
    icon: '🥥',
    retailPrice: 25.00,
    retailUnit: 'pz',
    wholesalePrice: 350.00,
    wholesaleUnit: 'Caja (20 pz)',
    description: 'Agua de coco helada y carne tierna.'
  },

  // --- VERDURAS ---
  {
    id: 'chile-habanero',
    name: 'Chile Habanero de Yucatán',
    category: 'verduras',
    isSeason: false,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🌶️',
    retailPrice: 45.00,
    retailUnit: 'kg',
    wholesalePrice: 390.00,
    wholesaleUnit: 'Huacal (10 kg)',
    description: 'El auténtico habanero yucateco, aroma inconfundible y picor óptimo.'
  },
  {
    id: 'tomate',
    name: 'Tomate Rojo Saladette',
    category: 'verduras',
    isSeason: false,
    isPopular: true,
    origin: 'Oxkutzcab / Dzan',
    icon: '🍅',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 320.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Tomate firme, rojo y fresco para ensaladas, salsas y guisados.'
  },
  {
    id: 'cebolla',
    name: 'Cebolla Blanca',
    category: 'verduras',
    isSeason: false,
    isPopular: true,
    origin: 'Región Sur',
    icon: '🧅',
    retailPrice: 20.00,
    retailUnit: 'kg',
    wholesalePrice: 340.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Cebollas limpias y de tamaño uniforme.'
  },
  {
    id: 'pepino',
    name: 'Pepino Blanco / Verde',
    category: 'verduras',
    isSeason: false,
    isPopular: true,
    origin: 'Oxkutzcab',
    icon: '🥒',
    retailPrice: 14.00,
    retailUnit: 'kg',
    wholesalePrice: 240.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Crujiente y lleno de frescura para ensaladas y botanas.'
  },
  {
    id: 'calabaza',
    name: 'Calabaza Local (Xmejen)',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🎃',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 280.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Calabacita tierna de la milpa yucateca.'
  },
  {
    id: 'chile-jalapeno',
    name: 'Chile Jalapeño',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🌶️',
    retailPrice: 25.00,
    retailUnit: 'kg',
    wholesalePrice: 320.00,
    wholesaleUnit: 'Huacal (15 kg)',
    description: 'Jalapeño verde fresco de excelente picor.'
  },
  {
    id: 'zanahoria',
    name: 'Zanahoria',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Región Sur',
    icon: '🥕',
    retailPrice: 16.00,
    retailUnit: 'kg',
    wholesalePrice: 280.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Zanahorias dulces y crujientes.'
  },
  {
    id: 'papa',
    name: 'Papa Blanca',
    category: 'verduras',
    isSeason: false,
    isPopular: true,
    origin: 'Nacional',
    icon: '🥔',
    retailPrice: 28.00,
    retailUnit: 'kg',
    wholesalePrice: 420.00,
    wholesaleUnit: 'Huacal (20 kg)',
    description: 'Papa de primera calidad para freír o cocer.'
  },
  {
    id: 'chayote',
    name: 'Chayote Sin Espina',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🍐',
    retailPrice: 18.00,
    retailUnit: 'kg',
    wholesalePrice: 280.00,
    wholesaleUnit: 'Huacal (18 kg)',
    description: 'Tiernos chayotes sin espina directos del campo.'
  },
  {
    id: 'cilantro',
    name: 'Cilantro Fresco',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Oxkutzcab',
    icon: '🌿',
    retailPrice: 8.00,
    retailUnit: 'manojo',
    wholesalePrice: 150.00,
    wholesaleUnit: 'Huacal (25 manojos)',
    description: 'Manojo de cilantro aromático recién cortado por la mañana.'
  },
  {
    id: 'ajo',
    name: 'Ajo Selección Especial',
    category: 'verduras',
    isSeason: false,
    isPopular: false,
    origin: 'Nacional',
    icon: '🧄',
    retailPrice: 10.00,
    retailUnit: 'cabeza',
    wholesalePrice: 350.00,
    wholesaleUnit: 'Caja (5 kg)',
    description: 'Cabezas grandes de ajo de intenso aroma.'
  }
];

const COVERAGE_AREAS = [
  { name: 'Oxkutzcab', time: '15 - 30 min', deliveryCost: 'Gratis en zona centro', badge: 'Matriz' },
  { name: 'Dzan', time: '30 - 45 min', deliveryCost: 'Costo mínimo $20 MXN', badge: 'Diario' },
  { name: 'Maní', time: '30 - 50 min', deliveryCost: 'Pueblo Mágico - $25 MXN', badge: 'Diario' },
  { name: 'Akil', time: '25 - 40 min', deliveryCost: 'Costo mínimo $20 MXN', badge: 'Diario' },
  { name: 'Emiliano Zapata', time: '20 - 35 min', deliveryCost: 'Comisaría Oxkutzcab - $15 MXN', badge: 'Diario' }
];

const BUSINESS_INFO = {
  name: 'Frutería Mis Dos Angelitos',
  phone: '9971326728',
  whatsappNumber: '529971326728',
  hours: 'Lunes a Domingo: 7:00 AM - 8:00 PM',
  location: 'Oxkutzcab, Yucatán, México',
  slogan: 'La frescura que llega hasta tu hogar'
};
